package ginyolith.aboutme

const val EXTRA_CATEGORY_ID = "categoryId"
const val EXTRA_DETAIL_ID = "detailId"

const val KEY_INSERT_DETAIL_RESULT = "INSERT_DETAIL_RESULT"
const val KEY_INSERT_CATEGORY_RESULT = "INSERT_CATEGORY_RESULT"

const val REQUEST_CODE_REFRESH_CATEGORY_LIST = 1
const val REQUEST_CODE_REFRESH_DETAIL_LIST   = 2